apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: testtopic1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5 #20 #5 #5 #7 #5 #10 #10 #5 #10 #5
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    min.insync.replicas: 1
      #message.timestamp.type: CreateTime #LogAppendTime
    message.timestamp.type: LogAppendTime
