apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
spec:
  restartPolicy: Never
  containers:
    - name: java-kafka-producer
      image: docker.io/mezzeddine/produceroldgrpc:v1   #twitterproducer:v1  #taxiproducernew:v3
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: testtopic1
        - name: DELAY_MS
          value: "1000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PRODUCER_ACKS
          value: "0"
        - name: ADDITIONAL_CONFIG
          value: |
                retries=100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latency
  name: latency1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency
          #image: docker.io/mezzeddine/twittertopo:v9 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist:v1   #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist:v2   #twittertopo:v10 #consumerbp:v00
          image: docker.io/mezzeddine/interceptordist12:v0   #twittertopo:v10 #consumerbp:v00


          ports:
          - containerPort: 8080
            name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: SLEEP
              value: "5"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=500

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latency
  name: latency2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency
          #image: docker.io/mezzeddine/twittertopo:v9 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist:v1   #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist23:v0   #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist2307:v1  #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist23:v1  #twittertopo:v10 #consumerbp:v00

          image: docker.io/mezzeddine/interceptordist23:v00

          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi



          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic2
            - name: GROUP_ID
              value: testgroup2
            - name: SLEEP
              value: "5"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=500

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latency
  name: latency3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency
          #image: docker.io/mezzeddine/twittertopo:v9 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist:v1   #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist23:v0   #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist2307:v1  #twittertopo:v10 #consumerbp:v00
          #image: docker.io/mezzeddine/interceptordist23:v1  #twittertopo:v10 #consumerbp:v00

          image: docker.io/mezzeddine/interceptordist3:v0



          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic3
            - name: GROUP_ID
              value: testgroup3
            - name: SLEEP
              value: "5"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=500
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grpcassignmentserver
  name: controllerandscaler
spec:
  restartPolicy: Never
  containers:

    - name: controllerandscaler
      #image: docker.io/mezzeddine/controllergraphbf:v1
      #image: docker.io/mezzeddine/controllergraphbf:v2
      #image: docker.io/mezzeddine/controllergraphbf:v3
      #image: docker.io/mezzeddine/controllergraphbf:v4
      #image: docker.io/mezzeddine/controllergraphbf:v7
      #image: docker.io/mezzeddine/controllergraphbf:v8
      #image: docker.io/mezzeddine/controllergraphbf:v9  # fup=1
      #image: docker.io/mezzeddine/controllergraphbf:v10  # fup=1,
      #image: docker.io/mezzeddine/controllergraphbf:v13  # fup=1, 10s
      #image: docker.io/mezzeddine/controllergraphbf:v25
      #image: docker.io/mezzeddine/controllergraphbf:v26
      image: docker.io/mezzeddine/controllergraphbf:v27


      # fup=1, 10s




      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi





      ports:
        - containerPort: 5002
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092


---
apiVersion: v1
kind: Service
metadata:
  name: assignmentservice #arrivalservice #assignmentservice
spec:
  selector:
    app: grpcassignmentserver
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: arrivalservice #assignmentservice
spec:
  selector:
    app: workload
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002