apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
spec:
  restartPolicy: Never
  containers:
    - name: java-kafka-producer
      #image: docker.io/mezzeddine/producerftest:v0  #produceroldgrpc:v1
      #image: docker.io/mezzeddine/omgrpc:v3
      #image: docker.io/mezzeddine/producertaxigrpc:v1
      #image: docker.io/mezzeddine/produceroldgrpc:v1
      #image: docker.io/mezzeddine/taxibatch40is:v0  #timely producer
      #image: docker.io/mezzeddine/taxi2h1640:v3   #timely producer
      #image: docker.io/mezzeddine/taxi2h40:v0   #timely producer
      #image: docker.io/mezzeddine/taxi200:v0   #producer taxi 250 no z
      image: docker.io/mezzeddine/taxiserver:v1
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: testtopic1
        - name: DELAY_MS
          value: "1000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PRODUCER_ACKS
          value: "0"
        - name: ADDITIONAL_CONFIG
          value: |
                retries=100


