# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: cluster-operator-metrics
#   labels:
#     app: strimzi
# spec:
#   selector:
#     matchLabels:
#       strimzi.io/kind: cluster-operator
#   namespaceSelector:
#     matchNames:
#       - default
#   podMetricsEndpoints:
#   - path: /metrics
#     port: http


# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: entity-operator-metrics
#   labels:
#     app: strimzi
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: entity-operator
#   namespaceSelector:
#     matchNames:
#       - default
#   podMetricsEndpoints:
#   - path: /metrics
#     port: healthcheck


# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: bridge-metrics
#   labels:
#     app: strimzi
# spec:
#   selector:
#     matchLabels:
#       strimzi.io/kind: KafkaBridge
#   namespaceSelector:
#     matchNames:
#       - default
#   podMetricsEndpoints:
#   - path: /metrics
#     port: rest-api


---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchExpressions:
      - key: "strimzi.io/kind"
        operator: In
        values: ["Kafka", "KafkaConnect", "KafkaMirrorMaker", "KafkaMirrorMaker2"]
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
    interval: 1s  
    relabelings:
    - separator: ;
      regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_pod_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace
---
  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: demoobservabilitypodmonitor
    labels:
      app: strimzi
  spec:
    selector:
      matchLabels:
        app: latency
    namespaceSelector:
      matchNames:
        - default
    podMetricsEndpoints:
      - path: /prometheus
        port: brom
        interval: 1s
---
  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: demoobservabilitypodmonitor1
    labels:
      app: strimzi
  spec:
    selector:
      matchLabels:
        app: workload
    namespaceSelector:
      matchNames:
        - default
    podMetricsEndpoints:
      - path: /prometheus
        port: brom
        interval: 1s